# Alya VPN - Client Configuration
[client]
server_host = "127.0.0.1"
server_port = 51821
local_proxy_port = 1080
passphrase = "change_me_to_a_secure_shared_passphrase_2026"
protocol = "tcp"
crypto_threads = 1
io_threads = 2
# DNS Protection:
#   true  - Route DNS queries through encrypted VPN tunnel to prevent ISP tampering/censorship (default).
#   false - Use local network DNS for direct connections.
tunnel_dns = true

[split_tunnel]
# Modes:
#   "all"     - Route all network traffic through the encrypted VPN tunnel.
#   "include" - (Whitelist) Only specified applications route through VPN; all others use direct local internet.
#   "exclude" - (Blacklist) Specified applications bypass VPN (direct internet); all other apps route through VPN.
mode = "include"
apps = [
    "Speedtest.exe",
    "speedtest.exe",
    "Speedtest",
    "speedtest",
    "Discord.exe",
    "discord.exe",
    "Discord",
    "discord",
    "Discord Helper",
    "discord helper",
    "ShipIt",
    "shipit",
    "mDNSResponder",
    "Chrome.exe",
    "Chrome",
    "chrome.exe",
    "chrome",
    "curl.exe",
    "curl"
]
